### ISSUE TITLE
Random dungeons posted

### ISSUE THREAD

**Issue by Jefferyasbell** [Arby69/LFGFilter#2]
Hello, I have been using LFGShout for some time now. I do not get any error when using that addon to post LFG in multiple channels at once by itself.... I found your addon and love it except for one thing.... now when I post the dungeons, I want to do, it adds a random TBC dungeon... usually, it puts in the Black Morass. I uninstall your addon and no more problems. I have used other addons for LFG options and this is the only one that affects LFGShout.  There is no Lua error so that's good, I guess. I'm not sure which one is the cultrate. I am leaning toward your addon, as the other works fine by its self.  the File I am using is 1.0.3-BCC.zip So I'd assume the version number is 1.0.3... Iv included a screen shot of what gets posted... as you can see My character is only level 47 so I am not able to do that dungeon yet. I love this addon. I love how it filters out the Dungeons I don't want to run and only highlights ones I want to do.
![LFGShout and LFG Filter with error](https://user-images.githubusercontent.com/33359689/127709891-a8c37903-d3dc-43f1-b270-53105d4478d5.jpg)

![LFGShout By its self No error](https://user-images.githubusercontent.com/33359689/127709654-1e74cee6-8e77-42e7-bea6-82850d9899b1.jpg)

**Comment by Arby69** [comment]
I can explain you what is happening there: As you are a Beastmaster Hunter you want to stress that in your post, so you use "BM" as a shortcut for your specialization.
Unfortunately, BM is also the most common abbreviation for "Black Morass".
LFGFilter takes any line that is posted to chat (so is yours) and complements it by the names of the dungeons it thinks it has recognized, so your line is expanded by the tag "[Black Morass]" (among others) in your chat window. Please note: This affects only the output in your chat window, the line is NOT posted that way to the public chats.
For that purpose, LFGFilter doesn't consume the chat line to change it and print it to your chat, but it uses a "filter function". That has many advantages, ie. it works on any chat window you create, regardless how many you have or where you use them.
That way, other Addons might also handle the chat, but then it comes to where order of the addons count. If LFGFilter gets the chat line first, changes it, and then LFGShout wants to parse it, it might find the falsely added [Black Morass] tag and thinks on its part, that dungeon was part of the request.

The ambiguity of BM for "Beast master" and "Black Morass" is a problem with LFGFilter. I don't see how to handle it properly. I could consider the player's level, but that only works if you are posting it yourself. WoW Classic doesn't have a reliable API to read the level of other players immediately. And then, as you grow and get into level range of that dungeon, the problem reoccurs.

Only way I can see: Players don't use "BM" as abbreviation for Beastmaster (I know, I can't demand that) or I remove the "BM" token from the LFGFilter's filter expressions. (I don't recommend you to remove it on your own. As BM is the common abbr. for Black Morass, it will break the complete Black Morass recognition filters. At least it should not produce LUA errors.)

**Comment by Arby69** [comment]
Okay, I tried to find out what LFGShout is doing and can give some more information.
As I understood, you use LFGShout to post your dungeon search to the chats. LFGFilter filters that chat line and recognizes the "BM" part for Beastmaster in it, so it thinks you also added the abbrev. for Black Morass and adds that tag to your chat output.
That is no problem at all. That shoutout is NOT sent to the rest of the World, the other players only see the chat line in the way you do when LFGFilter is not active (unless they use LFGFilter themselves).
LFGFilter only affects YOUR chat windows, not that of the other players when they don't have it. I hope, you better understand now what is happening.

**Comment by Jefferyasbell** [comment]
thanks for the clarification
